"""Init database

Revision ID: 1793cbcffaf5
Revises: 
Create Date: 2019-12-20 20:34:21.880460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1793cbcffaf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('secret_question', sa.String(length=128), nullable=True),
    sa.Column('secret_answer_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dictionary_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spelling', sa.String(length=128), nullable=True),
    sa.Column('definition', sa.String(length=550), nullable=True),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synonyms',
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('synonym_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['synonym_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synonyms')
    op.drop_table('words')
    op.drop_table('dictionaries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
