"""Added learning index

Revision ID: 34fad820c49a
Revises: 3f70a960d5ad
Create Date: 2020-01-08 16:26:07.030858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fad820c49a'
down_revision = '3f70a960d5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_index', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'learning_index', 'words', ['word_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learning_index', type_='foreignkey')
    op.drop_column('learning_index', 'word_id')
    # ### end Alembic commands ###
