"""GameType in CurrentGame

Revision ID: 50e66e817ed9
Revises: a8fdf7e29ada
Create Date: 2020-01-17 21:13:53.664412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e66e817ed9'
down_revision = 'a8fdf7e29ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_game', sa.Column('game_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_game', 'game_type')
    # ### end Alembic commands ###
