"""Added table for current game

Revision ID: 53da096e30fe
Revises: 34fad820c49a
Create Date: 2020-01-12 18:15:28.882531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53da096e30fe'
down_revision = '34fad820c49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_started', sa.DateTime(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_game_game_started'), 'current_game', ['game_started'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_game_game_started'), table_name='current_game')
    op.drop_table('current_game')
    # ### end Alembic commands ###
