"""tables dictionaries, words

Revision ID: 7682bfa3006a
Revises: 9c375181a0d5
Create Date: 2019-12-15 09:22:30.372726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7682bfa3006a'
down_revision = '9c375181a0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dictionary_name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['db_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spelling', sa.String(length=128), nullable=True),
    sa.Column('definition', sa.String(length=550), nullable=True),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['db_dictionaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synonyms',
    sa.Column('synonym_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['synonym_id'], ['db_words.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synonyms')
    op.drop_table('db_words')
    op.drop_table('db_dictionaries')
    # ### end Alembic commands ###
