"""Added description to dictionary

Revision ID: 95f53ebc47e3
Revises: c0119683b760
Create Date: 2019-12-20 10:01:10.492927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f53ebc47e3'
down_revision = 'c0119683b760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_dictionaries', sa.Column('description', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_dictionaries', 'description')
    # ### end Alembic commands ###
