"""Additional columns in RevisionGame table

Revision ID: a8fdf7e29ada
Revises: c952899647f9
Create Date: 2020-01-15 15:51:29.454402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8fdf7e29ada'
down_revision = 'c952899647f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_game', sa.Column('game_completed', sa.Boolean(), nullable=True))
    op.add_column('current_game', sa.Column('game_date_completed', sa.DateTime(), nullable=True))
    op.add_column('current_game', sa.Column('game_date_started', sa.DateTime(), nullable=True))
    op.drop_index('ix_current_game_game_started', table_name='current_game')
    op.drop_column('current_game', 'game_started')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_game', sa.Column('game_started', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_current_game_game_started', 'current_game', ['game_started'], unique=False)
    op.drop_column('current_game', 'game_date_started')
    op.drop_column('current_game', 'game_date_completed')
    op.drop_column('current_game', 'game_completed')
    # ### end Alembic commands ###
