"""Added relationship in dictionaries

Revision ID: c0119683b760
Revises: 7682bfa3006a
Create Date: 2019-12-19 21:31:48.724023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0119683b760'
down_revision = '7682bfa3006a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synonyms', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'synonyms', 'db_words', ['word_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'synonyms', type_='foreignkey')
    op.drop_column('synonyms', 'word_id')
    # ### end Alembic commands ###
