"""Correct answers in current game

Revision ID: f273e939b2c7
Revises: 50e66e817ed9
Create Date: 2020-02-03 20:32:41.249030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f273e939b2c7'
down_revision = '50e66e817ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_game', sa.Column('correct_answers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_game', 'correct_answers')
    # ### end Alembic commands ###
